### PR TITLE
add disableAdornment, disableLabel to getInputProps

### PR DESCRIPTION
**Pull request by caub**

### CODE REVIEW

**Comment by techniq** [comment]
@caub Instead of `disableLabel` how about we use the existance of a passed label to include or not...

```js
{label && <InputLabel {...labelProps}>{label}</InputLabel>}
```

For `disabledAdornment` this should also be able to be accomplished with
```js
<StarWarsSelect getInputProps={() => ({ endAdornment: null })} />
```
I'd rather leave go that route unless I'm missing something.  After the change to `label`, this example should accomplish what you are looking for I believe.

**Comment by caub** [comment]
Good points, thanks

**Comment by techniq** [comment]
I just published this as `1.0.0-9` and can be installed using `yarn add mui-downshift@next`.

Once we have a good example story for multi-select (#5, including chips and "# selected") and option groups (#20) I plan to release `1.0.0`.  I've been holding off incase there were any breaking changes required to support those use cases.

Thanks for your contributions to the project 😄

**Comment by caub** [comment]
@techniq you're welcome

for the multi-select, I'd avoid to toggle an item when [selecting it again](https://github.com/techniq/mui-downshift/blob/multi-select/stories/components/StarWarsMultiSelect.js#L60) (rather filtering it from `filteredItems`, or removing and adding it in last position)

Also, it's not easy, but the dropdown should always be opened as long as the input has focus. Sometimes I have to blur and refocus it (or I could type in too) to reopen it after a selecting an item)

I'm working on the multi-group-select, but without downshift for now, in pure mui with react-popper, I'll post a codesandbox, and hopefully use your lib, when I'm more familiar with downshift

**Comment by techniq** [comment]
@caub To keep the menu open, you could look at using downhift's [stateReducer](https://dataprocessor.app.chhi.org) prop, which shows this very example.

I'd like to look into toggling, but also considered showing the selected items at the top of the list and it's makes more sense to see the selected items at the top upon opening the menu (or if the selections were set ahead of time, for instance from the query string).  The trouble comes to not have the list jump when you put them at the top, and also not having the item "disappear" when you select it and it moves to the top (so you would kind of need both - the item added to the top without affecting what is shown, but also show the entry at the top for quick deselection (especially if you are paginating the items from the server).

Anyways, I look forward to your example, and thanks again :)

**Comment by caub** [comment]
@techniq in my project I did it without downshift, with this way: https://codesandbox.io/s/yp4o52j6mx

**Comment by techniq** [comment]
Throwing an error... looks like `Dropdown` is empty

image

**Comment by caub** [comment]
should work, tested

**Comment by techniq** [comment]
It works now, that was weird 😕 Looks nice 😄

Some initial feedback:

## Setting a `min-width` on your `<input />` will keep it from getting cut off (and flex-wrap'd sooner)
Before
image

After
image

## I noticed arrow keys do not allow you to make selections
Downshift provides this (not to push you to use it, but might save you from implementing it yourself)

## It would be nice to be able to press backspace with an empty input and remove items
See [here](https://teamwertarbyte.github.io/material-ui-chip-input/?selectedKind=ChipInput&selectedStory=with%20some%20chips&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel) for an example.  It focuses the chip first, then removes it.

I've considered providing higher level components are part of miu-downshift (but still exposing `MuiDownshift`) to make it a little easier to use (especially for simple use cases, see #12 ).  I might look into exposing a `MultiSelect` and possible `MultiSelectGroup` like you have, although even multi-select can be multi-faceted (chips, # selected with checkboxes, close after selection or not, etc) which is one reason I wanted to avoid it so far (I won't be able to support everyones use case, so hoped providing enough examples would at least give someone a way to copy/paste and iterate.

Anyways, sorry for the ramble.  Looks good, and let me know if you need anything else from me.  If you decide to use downshift and would want to PR something back to the project, I'd be most obliged.

**Comment by caub** [comment]
Oh thanks, interesting

I've tried to add those left/right and delete selection in the first multi-select https://codesandbox.io/s/yp4o52j6mx it's 

I'm sure it's possible to do it with Downshift, it basically replaces my Dropdown, it's quite equivalent, I was just not able to understand yet all the downshift flow, but yes, I'm sure you can be able to make those components. You'll need to be able to adjust downshift's width, I gave it a try, but not for long

Best, thanks

**Pull request merged**
